---
- name: Configure journald
  become: true
  tags:
    - journal
    - journald
    - journalctl
  block:
    - name: Configure journal access for selected users
      user:
        name: "{{ item }}"
        groups: "{{ journalctl_group }}"
        append: true
      with_items: "{{ journalctl_users }}"